    CREATE TABLE MODULE_OPTION
    (
      MODULE_ID              VARCHAR2(100) NOT NULL,
      OPTION_NAME            VARCHAR2(150) NOT NULL,
      OPTION_VALUE           VARCHAR2(150) NULL,
      OPTION_TITLE           VARCHAR2(150) NULL,
      OPTION_ORDER           NUMBER(11)
    );

    ALTER TABLE MODULE_OPTION
      ADD CONSTRAINT  MODULE_OPTION_PK PRIMARY KEY (MODULE_ID, OPTION_NAME);

    CREATE  INDEX MODULE_OPTION_ORDER_1 ON MODULE_OPTION (OPTION_ORDER   ASC);

    COMMENT ON TABLE MODULE_OPTION IS '모듈 옵션';

    COMMENT ON COLUMN MODULE_OPTION.MODULE_ID IS '모듈ID';
    COMMENT ON COLUMN MODULE_OPTION.OPTION_NAME IS '옵션명';
    COMMENT ON COLUMN MODULE_OPTION.OPTION_VALUE IS '옵션값';
    COMMENT ON COLUMN MODULE_OPTION.OPTION_TITLE IS '이름';
    COMMENT ON COLUMN MODULE_OPTION.OPTION_ORDER IS '순서';